### ISSUE TITLE
Bug with *) > Ἁ in Perseus mode

### ISSUE THREAD

**Issue by JPapir** [dgkontopoulos/Encode-BetaCode#2]
Hi @dgkontopoulos ,
On the line 95 : 
        `$input =~ s/[*][)]a/Ἁ/gi;`
Should be : 
       ` $input =~ s/[*][)]a/Ἀ/gi;`

Thanks for this useful module in Perl !

**Comment by dgkontopoulos** [comment]
Hi @JPapir,

Thank you very much for the kind words and for reporting the bugs! They have now been fixed in version 0.11.

Cheers,
Dimitrios
